name: native_bridge_kit_dart_gen
description: Dart code generator for Android and iOS native_bridge_kit contracts. Generates Dart implementation files (.g.dart) from @NativeBridge-annotated contracts.
version: 0.1.4
repository: https://github.com/handertool/native_bridge_kit
issue_tracker: https://github.com/handertool/native_bridge_kit/issues

environment:
  sdk: ^3.11.5

dependencies:
  analyzer: ">=6.0.0 <8.0.0"
  build: ^2.4.0
  native_bridge_kit_annotation: ^0.1.4
  source_gen: ^1.5.0

dev_dependencies:
  test: ^1.25.0
  build_test: ^2.2.0
