// Generated by native_bridge_kit_ios_gen
// Generated scaffold - implement the marked handlers.

import Flutter

class DeviceInfoBridgeHandler {
  private let methodChannel: FlutterMethodChannel

  init(controller: FlutterViewController) {
    self.methodChannel = FlutterMethodChannel(
      name: "device_info",
      binaryMessenger: controller.binaryMessenger
    )
    self.battery_levelEventChannel = FlutterEventChannel(
      name: "device_info/battery_level",
      binaryMessenger: controller.binaryMessenger
    )
  }

  func setupChannelHandlers() {
    methodChannel.setMethodCallHandler { (call, result) in
      switch call.method {
        case "get_model":
          self.handleGet_model(call, result: result)
        case "get_os_version":
          self.handleGet_os_version(call, result: result)
        default:
          result(FlutterMethodNotImplemented)
        }
    }
    registerBattery_levelEventChannel()
  }

  private let battery_levelEventChannel: FlutterEventChannel

  private func registerBattery_levelEventChannel() {
    battery_levelEventChannel.setStreamHandler(Battery_levelStreamHandler())
  }

  private func handleGet_model(
    _ call: FlutterMethodCall,
    result: @escaping FlutterResult
  ) {
    // MARK: - BEGIN USER CODE - modify this method as needed
    // TODO: Implement async handler for get_model
    // For async work, use DispatchQueue or async/await
    let response: Any? = nil // TODO: Implement
    result(response)
    // MARK: - END USER CODE
  }


  private func handleGet_os_version(
    _ call: FlutterMethodCall,
    result: @escaping FlutterResult
  ) {
    // MARK: - BEGIN USER CODE - modify this method as needed
    // TODO: Implement async handler for get_os_version
    // For async work, use DispatchQueue or async/await
    let response: Any? = nil // TODO: Implement
    result(response)
    // MARK: - END USER CODE
  }


  private final class Battery_levelStreamHandler: NSObject, FlutterStreamHandler {
    private var eventSink: FlutterEventSink?

    func onListen(withArguments arguments: Any?, eventSink events: @escaping FlutterEventSink) -> FlutterError? {
      // MARK: - BEGIN USER CODE - start native events and call eventSink
      self.eventSink = events
      // MARK: - END USER CODE
      return nil
    }

    func onCancel(withArguments arguments: Any?) -> FlutterError? {
      self.eventSink = nil
      // TODO: Stop listening to native events
      return nil
    }
  }


}
