// Generated by native_bridge_kit_android_gen
// Generated scaffold - implement the marked handlers.

package com.example.pet_project.bridge

import io.flutter.embedding.engine.FlutterEngine
import io.flutter.plugin.common.MethodCall
import io.flutter.plugin.common.MethodChannel
import io.flutter.plugin.common.EventChannel

class DeviceInfoBridgeHandler(
  private val flutterEngine: FlutterEngine
) {
  private val methodChannel = MethodChannel(
    flutterEngine.dartExecutor.binaryMessenger,
    "device_info"
  )

  fun setupChannelHandlers() {
    methodChannel.setMethodCallHandler { call, result ->
      try {
        when (call.method) {
          "get_model" -> handleGet_model(call, result)
          "get_os_version" -> handleGet_os_version(call, result)
          else -> result.notImplemented()
        }
      } catch (e: Exception) {
        result.error("ERROR", e.message ?: "Unknown error", null)
      }
    }
  }

  private val battery_levelEventChannel = EventChannel(
    flutterEngine.dartExecutor.binaryMessenger,
    "device_info/battery_level"
  )

  private val battery_levelStreamHandler = Battery_levelStreamHandler()

  private fun registerEventChannels() {
    battery_levelEventChannel.setStreamHandler(battery_levelStreamHandler)
  }

  init {
    registerEventChannels()
  }

  private fun handleGet_model(
    call: MethodCall,
    result: MethodChannel.Result
  ) {
    // BEGIN USER CODE - modify this method as needed
    try {
      // TODO: Implement async handler for get_model
      // For async work, you may want to use thread or coroutines
      val response: Any? = null // TODO: Implement
      result.success(response)
    } catch (e: Exception) {
      result.error("get_model_error", e.message, null)
    }
    // END USER CODE
  }


  private fun handleGet_os_version(
    call: MethodCall,
    result: MethodChannel.Result
  ) {
    // BEGIN USER CODE - modify this method as needed
    try {
      // TODO: Implement async handler for get_os_version
      // For async work, you may want to use thread or coroutines
      val response: Any? = null // TODO: Implement
      result.success(response)
    } catch (e: Exception) {
      result.error("get_os_version_error", e.message, null)
    }
    // END USER CODE
  }


  private inner class Battery_levelStreamHandler : EventChannel.StreamHandler {
    override fun onListen(
      arguments: Any?,
      events: EventChannel.EventSink?
    ) {
      // BEGIN USER CODE - modify this method as needed
      // TODO: Start listening to native events and emit via events?.success()
      // END USER CODE
    }

    override fun onCancel(arguments: Any?) {
      // TODO: Stop listening to native events
    }
  }


}
